# Generated by Django 4.2.5 on 2023-09-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_bookmark_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='app.author'),
        ),
    ]
